spring:
  jpa:
    open-in-view: false

management:
#  server:
#    port: 9092
  endpoint:
    health:
      show-components: always
     #show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
#      base-path: "/manage"